name: firestone-book-locater
recipe: lamp
config:
  webroot: .
  php: '5.5'
services:
  html:
    type: apache:2.2
    ssl: false
    ports:
      - '8081:80'
  database:
    type: mariadb
    creds:
      database: locator_production
      user: locator
      password: locator
  database1:
    type: mariadb
    creds:
      database: locator_stage
      user: locator
      password: locator
