CREATE TABLE lctr_Octavos_cn_lcsort LIKE lctr_Octavos_cn;
INSERT lctr_Octavos_cn_lcsort SELECT * FROM lctr_Octavos_cn;
update lctr_Octavos_cn_lcsort set right_cn=Replace(Replace(Replace(right_cn,'  ',' '),'  ',' '),'  ',' ');
update lctr_Octavos_cn_lcsort set left_cn=Replace(Replace(Replace(left_cn,'  ',' '),'  ',' '),'  ',' ');
update lctr_Octavos_cn_lcsort set left_cn=Replace(left_cn,' ','.');
update lctr_Octavos_cn_lcsort set right_cn=Replace(right_cn,' ','.');
update lctr_Octavos_cn_lcsort set right_cn=Replace(right_cn,'..','.');
update lctr_Octavos_cn_lcsort set left_cn=Replace(left_cn,'..','.');

update lctr_Octavos_cn_lcsort set left_cn='HD.0078' where id_cn = 1270;
update lctr_Octavos_cn_lcsort set left_cn='F.0786.W.334' where id_cn = 1219;
update lctr_Octavos_cn_lcsort set left_cn='DA.0670.N.7.B' where id_cn = 1269;
update lctr_Octavos_cn_lcsort set left_cn='D.0756' where id_cn = 1173;
update lctr_Octavos_cn_lcsort set left_cn='BP.0064.' where id_cn = 1268;
update lctr_Octavos_cn_lcsort set left_cn='BL.0690' where id_cn = 1267;
update lctr_Octavos_cn_lcsort set left_cn='PQ.0540' where id_cn = 1240;
update lctr_Octavos_cn_lcsort set left_cn='PN.0171.P.8' where id_cn = 1242;
update lctr_Octavos_cn_lcsort set left_cn='B.2430.B344' where id_cn = 1161;
update lctr_Octavos_cn_lcsort set left_cn='DA.0670.N7.B' where id_cn = 1269;
update lctr_Octavos_cn_lcsort set left_cn='E.018561.G8' where id_cn = 1263;
update lctr_Octavos_cn_lcsort set left_cn='PT.2340.H47' where id_cn = 1262;
update lctr_Octavos_cn_lcsort set left_cn='PQ.4876.R387' where id_cn = 1239;

update lctr_Octavos_cn_lcsort set right_cn='BL.0689~' where id_cn = 1266;
update lctr_Octavos_cn_lcsort set right_cn='BP.0063~' where id_cn = 1267;
update lctr_Octavos_cn_lcsort set right_cn='D.0755~' where id_cn = 1096;
update lctr_Octavos_cn_lcsort set right_cn='DA.0670.N.7.A~' where id_cn = 1173;
update lctr_Octavos_cn_lcsort set right_cn='F.0786.W.324~' where id_cn = 1220;
update lctr_Octavos_cn_lcsort set right_cn='HD.0077~' where id_cn = 1222;
update lctr_Octavos_cn_lcsort set right_cn='PITN.0999' where id_cn = 64;
update lctr_Octavos_cn_lcsort set right_cn='PN.0171.P~' where id_cn = 1243;
update lctr_Octavos_cn_lcsort set right_cn='PQ.0538~' where id_cn = 1250;
update lctr_Octavos_cn_lcsort set right_cn='B.2430.B343~' where id_cn = 1177;
update lctr_Octavos_cn_lcsort set right_cn='DA.0670.N7.A~' where id_cn = 1173;
update lctr_Octavos_cn_lcsort set right_cn='E.018561.G7~' where id_cn = 1217;
update lctr_Octavos_cn_lcsort set right_cn='PT.2340.H46~' where id_cn = 1130;
update lctr_Octavos_cn_lcsort set right_cn='PQ.4876.R386~' where id_cn = 1240;
rename table lctr_Octavos_cn to lctr_Octavos_cn_orig;
rename table lctr_Octavos_cn_lcsort to lctr_Octavos_cn;
